[project]
name = "easydocker"
version = "0.1.0"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]
description = "Opus analysis project"

[feature.easydocker]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[feature.easydocker.dependencies]
python = ">=3.8"  
pip = "*"        
autogrid = "4.2.9"
cctbx-base = "2024.8"
freetype = "2.13.3"
gemmi = "0.7.1"
libglu = "9.0.3"
libpng = "1.6.47"
meeko = "0.6.1"
molscrub = "0.1.1"
numpy = "1.26.4"
openff-toolkit = "0.16.4"
openmm = "7.7.0"
openmmforcefields = "0.14.1"
pdbfixer = "1.8.1"
prody = "2.4.1"
prolif = "2.0.3"
py3dmol = "2.4.2"
pymol-open-source = "3.1.0"
rdkit = "2024.03.6"
scipy = "1.15.2"
vina = "1.2.6"

[feature.easydocker.pypi-dependencies]

[environments]
easydocker = { features = ["easydocker"], solve-group = "easydocker" }


